### PR TITLE
Small clean up and added some tests

### PR DESCRIPTION
**Pull request by gurustron**
- Removed rethrowing exceptions (fixes https://github.com/fpanaccia/Wkhtmltopdf.NetCore/issues/29)
- Very minor refactorings in some places.
- Added some tests

### CODE REVIEW

**Comment by gurustron** [comment]
@fpanaccia  can you please fix  AppVeyor build  and tests to it?

**Comment by fpanaccia** [comment]
Hi!, i had planning to delete AppVeyor and use github actions...i just did the upload...i will add the testing in the weekend

**Comment by gurustron** [comment]
@fpanaccia  Thank you!

**Comment by gurustron** [comment]
@fpanaccia  can you somehow setup actions to be run only on main repo, not the forks?

**Comment by fpanaccia** [comment]
it seems that there is a workaround....but i think i gonna remove the action and use azure devops

**Pull request merged**
