### PR TITLE
Allow absolute/system-wide path

### PR DESCRIPTION
**Pull request by gurustron**
Based on https://github.com/fpanaccia/Wkhtmltopdf.NetCore/pull/31.
Resolves https://github.com/fpanaccia/Wkhtmltopdf.NetCore/issues/27.

- Added `IWkhtmltopdfPathProvider` and few implementations, including `ExactPathProvider` allowing users to provide any path including system-wide one.
- Marked old DI method as obsolete. Added new one requiring `IMvcBuilder`.
- Introduced `IWkhtmlDriver`.

### CODE REVIEW

**Comment by gurustron** [comment]
@fpanaccia 
Just FYI:
Needed to add:
```
    - name: CHMOD
      run: chmod +x Wkhtmltopdf.NetCore/Rotativa/Linux/wkhtmltopdf
```
to the github actions so tests will be able to pass

**Comment by fpanaccia** [comment]
@gurustron is this PR ready? because im gonna do another modifications and i dont want to generate conflicts

**Comment by gurustron** [comment]
@fpanaccia  yes, it is ready for review and if you don't have any objections - merging =)

**Comment by fpanaccia** [comment]
Perfect! I have a few concerns, but dont worry i will merge it, and review it.

Thanks for your great work!

**Comment by gurustron** [comment]
@fpanaccia  my pleasure!

**Pull request merged**
